### ISSUE TITLE
Build Broken Unit Test

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#1526]
AllReady.UnitTest.Areas.Admin.ViewModels.Validators.Task.TaskEditViewModelValidatorShould.ReturnNoErrorForItineraryTaskWhenModelsDatesAreValid
in AllReady.UnitTest.DLL
Error message:
Assert.True() Failure
Expected: True
Actual:   False

Stack Trace:
   at AllReady.UnitTest.Areas.Admin.ViewModels.Validators.Task.TaskEditViewModelValidatorShould.<ReturnNoErrorForItineraryTaskWhenModelsDatesAreValid>d__6.MoveNext() in C:\projects\allready\AllReadyApp\Web-App\AllReady.UnitTest\Areas\Admin\ViewModels\Validators\Task\TaskEditViewModelValidatorShould.cs:line 149
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Happened after merging #1494 and #1524

**Comment by tonysurma** [comment]
test is here for handy linking [unit test that is broken](https://github.com/HTBox/allReady/blob/a624cac1ed5866c977141efbd4c1682e24f468da/AllReadyApp/Web-App/AllReady.UnitTest/Areas/Admin/ViewModels/Validators/Task/TaskEditViewModelValidatorShould.cs#L133)

**Comment by dpaquette** [comment]
This can be closed

**Comment by tonysurma** [comment]
closed in #1528
