### ISSUE TITLE
SqlException on first run: Invalid object name 'Location'.

### ISSUE THREAD

**Issue by BBosman** [HTBox/allReady#1844]
I made a fresh clone of the repository, read the [documentation](https://github.com/HTBox/allReady/wiki/Developer-Setup), installed all the bits, changed the config to point at an empty database and ran `dotnet run`, which resulted in the following error message:
```
dbug: Hangfire.SqlServer.ExpirationManager[0]
      Removing outdated records from the 'List' table...
fail: Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler[1]
      An exception occurred in the database while iterating the results of a query.
      System.Data.SqlClient.SqlException: Invalid object name 'Location'.
         at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
         at System.Data.SqlClient.SqlDataReader.get_MetaData()
         at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
         at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
         at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
         at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
         at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers)
         at lambda_method(Closure , QueryContext )
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass20_0`1.<CompileQueryCore>b__0(QueryContext qc)
      ClientConnectionId:ca173e0f-1948-4b1b-a16e-caf67375417c
      Error Number:208,State:1,Class:16
System.Data.SqlClient.SqlException: Invalid object name 'Location'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass20_0`1.<CompileQueryCore>b__0(QueryContext qc)
ClientConnectionId:ca173e0f-1948-4b1b-a16e-caf67375417c
Error Number:208,State:1,Class:16

Unhandled Exception: System.Data.SqlClient.SqlException: Invalid object name 'Location'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass20_0`1.<CompileQueryCore>b__0(QueryContext qc)
   at System.Linq.Queryable.Any[TSource](IQueryable`1 source)
   at AllReady.DataAccess.SampleDataGenerator.InsertTestData()
   at AllReady.Startup.<Configure>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
trce: Hangfire.SqlServer.ExpirationManager[0]
      Outdated records removed from the 'List' table.
dbug: Hangfire.SqlServer.ExpirationManager[0]
      Removing outdated records from the 'Set' table...
```

If I manually run `dotnet ef database update` before `dotnet run` everything works, so it appears it's trying to access database tables before migrations have run.

**Comment by tonysurma** [comment]
ping @mgmccarthy is there a hangfire db connection or something needed maybe that isn't in the instructions?

**Comment by mgmccarthy** [comment]
@tonysurma cc @BBosman

if the machine it's running on is not a windows machine with sql server installed, then the developer will have to go in an manually configure a connection out to something like Azure sql server in order to have hangfire run.

Looking at the stack trace, the problem here looks to be that there is an class/entity called `Location` that is no longer in the solution?

**Comment by mgmccarthy** [comment]
and fyi, I don't know how `dotnet run` works...

is it the same thing as hitting F5 in the VS IDE? If not, then I'm not too sure if all the items that Startup.cs are being fired in the right order.

**Comment by BBosman** [comment]
I figured out what's happening.

Startup.cs has:
```cs
if (!env.IsProduction())
{
  context.Database.Migrate();
}

// More code...

if (Configuration["SampleData:InsertSampleData"] == "true")
{
  sampleData.InsertTestData();
}
```

As you can see the Migration is done before the insertion of the test data, but only when not running in Production. And the default is Production...

I don't know what the design decision was for that `IsProduction` check? Either that needs to change, or the documentation needs to be extended to mention setting the `Environment` to `Production`.

**Comment by tonysurma** [comment]
What OS etc. are you running? In all cases to date is production is false unless explicitly set to production...  Thanks

**Comment by BBosman** [comment]
Microsoft Windows [Version 10.0.14393] (and using Visual Studio Code 1.10.1)

By default Asp.Net Core looks at the environment variable `ASPNETCORE_ENVIRONMENT` to see in which environment it should run and if it isn't set it will use `Production`.

Visual Studio generates a `Properties\launchSetting.json`, which "sets" the environment to `Development` if you start the site though Visual Studio.

Visual Studio Code has a similar construct using `.vscode\launch.json`.

When running `dotnet run` from the command-line you'll manually have to do something like `set ASPNETCORE_ENVIRONMENT=Development` first.

The repository has a `Properties\launchSetting.json` pointing to `Production`, so if you're only using Visual Studio you'll get `Production`, but not when running from Visual Studio Code or the command-line.

**Comment by tonysurma** [comment]
Thank you for the details!

**Comment by tonysurma** [comment]
Not sure how many (if any)  have tried with dotnet run so thank you for documenting.  Sounds like we need to update documentation then.  I'll do a bit more research to see if there is some way to set that per app other than ENV var.  Thanks again

**Comment by tonysurma** [comment]
Looks like a PR with code in here for memory defaults should find this up if it works

http://stackoverflow.com/questions/37322565/dotnet-run-or-dotnet-watch-with-development-environment-from-command-line

**Comment by EmilyLuijbregts** [comment]
@BBosman - does the article provided by @tonysurma work? If it does - @tonysurma Can we add this to the documentation or notes?

**Comment by tonysurma** [comment]
@EmilyLuijbregts we can go one further and implement a change in the code in https://github.com/HTBox/allReady/blob/master/AllReadyApp/Web-App/AllReady/Program.cs and use the code from this answer http://stackoverflow.com/a/39131944 and it would default to development without any work on the dev's part and be able to be changed on the command line

**Comment by BBosman** [comment]
I think forcing it to run in Development mode by default is the wrong way to go. Production is the default for a reason. 

I would be more in favor of tweaking the code a bit so it doesn't crash on startup on whichever environment Dev/Prod you decide to start the application. 

My suggestion would be to tweak the Migration code to something like this:
```
if (!env.IsProduction() || Configuration["SampleData:InsertSampleData"] == "true")
{
  context.Database.Migrate();
}
```

This way it will do the migrations if you want the test seed data, and/or are running in Development.

**Comment by tonysurma** [comment]
@BBosman I like that - it clears the dev by default concern (good point) and makes a good first run experience that won't affect production (we don't even set that InsertSampleData item in prod config let alone set it to true.

Sounds like a plan!
