### ISSUE TITLE
Typescript Build Errors

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1859]
It appears since PR #1851 the local development build is failing.

In the output from task runner explorer I see
```
Failed to run "C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\Gulpfile.js"...
cmd.exe /c gulp --tasks-simple
module.js:327
    throw err;
    ^
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\node_modules\gulp-typescript\release\main.js:7:10)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

Part of the build output looks like this
```
3>  C:\Program Files\dotnet\dotnet.exe build "C:\Projects\Other\HTBox-AllReady\AllReadyApp\AllReady.NotificationsWebJob" --configuration Debug --no-dependencies --no-incremental
3>  Project AllReady.NotificationsWebJob (.NETFramework,Version=v4.6) will be compiled because project is not safe for incremental compilation. Use --build-profile flag for more information.
3>  Compiling AllReady.NotificationsWebJob for .NETFramework,Version=v4.6
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(1,1): error TS6053: Build:File 'C:/Projects/Other/HTBox-AllReady/AllReadyApp/Web-App/AllReady/node_modules/bingmaps/scripts/MicrosoftMaps/Microsoft.Maps.d.ts' not found.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(15,22): error TS2503: Build:Cannot find namespace 'Microsoft'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(16,37): error TS2503: Build:Cannot find namespace 'Microsoft'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(23,22): error TS2503: Build:Cannot find namespace 'Microsoft'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(43,5): error TS2304: Build:Cannot find name '$'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(57,29): error TS2304: Build:Cannot find name 'JQueryXHR'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(63,46): error TS2503: Build:Cannot find namespace 'Microsoft'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(66,16): error TS2304: Build:Cannot find name 'Microsoft'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(72,57): error TS2503: Build:Cannot find namespace 'Microsoft'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(72,105): error TS2503: Build:Cannot find namespace 'Microsoft'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(75,33): error TS2503: Build:Cannot find namespace 'Microsoft'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(76,5): error TS2304: Build:Cannot find name '$'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(77,36): error TS2503: Build:Cannot find namespace 'Microsoft'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(77,66): error TS2304: Build:Cannot find name 'Microsoft'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(79,22): error TS2503: Build:Cannot find namespace 'Microsoft'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(79,51): error TS2304: Build:Cannot find name 'Microsoft'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(85,34): error TS2503: Build:Cannot find namespace 'Microsoft'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(88,20): error TS2503: Build:Cannot find namespace 'Microsoft'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(89,5): error TS2304: Build:Cannot find name '$'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(90,23): error TS2503: Build:Cannot find namespace 'Microsoft'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(90,53): error TS2304: Build:Cannot find name 'Microsoft'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(93,18): error TS2503: Build:Cannot find namespace 'Microsoft'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(93,47): error TS2304: Build:Cannot find name 'Microsoft'.
3>  Compilation succeeded.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(98,15): error TS2503: Build:Cannot find namespace 'Microsoft'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(98,45): error TS2304: Build:Cannot find name 'Microsoft'.
3>      0 Warning(s)
3>      0 Error(s)
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(102,39): error TS2503: Build:Cannot find namespace 'Microsoft'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(102,83): error TS2503: Build:Cannot find namespace 'Microsoft'.
3>  Time elapsed 00:00:02.9563035
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(110,26): error TS2304: Build:Cannot find name 'Microsoft'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\ts\mappingTools.ts(4,19): error TS2304: Build:Cannot find name 'Microsoft'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\ts\mappingTools.ts(71,13): error TS2304: Build:Cannot find name '$'.
```

I also see this in the solution explorer
![image](https://cloud.githubusercontent.com/assets/3669103/23797715/10e35d22-0599-11e7-89c5-379ec5fcfd11.png)

If I roll back to the prior commit, it's all fine.

cc/ @BBosman @stimms

**Comment by BBosman** [comment]
It looks like a couple of npm packages are out of sync on your machine. 

Try doing a package restore on the npm node or run a npm install from the commandline.

**Comment by stevejgordon** [comment]
@BBosman After re-opening VS I saw it restore and no longer getting an error in solution explorer. On build I now get

```
1>------ Build started: Project: AllReady.Core, Configuration: Debug Any CPU ------
1>  C:\Program Files\dotnet\dotnet.exe build "C:\Projects\Other\HTBox-AllReady\AllReadyApp\AllReady.Core" --configuration Debug --no-dependencies
1>  Project AllReady.Core (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
2>------ Build started: Project: AllReady, Configuration: Debug Any CPU ------
3>------ Build started: Project: AllReady.NotificationsWebJob, Configuration: Debug Any CPU ------
3>  C:\Program Files\dotnet\dotnet.exe build "C:\Projects\Other\HTBox-AllReady\AllReadyApp\AllReady.NotificationsWebJob" --configuration Debug --no-dependencies
3>  Project AllReady.NotificationsWebJob (.NETFramework,Version=v4.6) was previously compiled. Skipping compilation.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(43,5): error TS2304: Build:Cannot find name '$'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(57,29): error TS2304: Build:Cannot find name 'JQueryXHR'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(76,5): error TS2304: Build:Cannot find name '$'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\js\site.ts(89,5): error TS2304: Build:Cannot find name '$'.
2>C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady\wwwroot\ts\mappingTools.ts(71,13): error TS2304: Build:Cannot find name '$'.
4>------ Build started: Project: AllReady.UnitTest, Configuration: Debug Any CPU ------
4>  C:\Program Files\dotnet\dotnet.exe build "C:\Projects\Other\HTBox-AllReady\AllReadyApp\Web-App\AllReady.UnitTest" --configuration Debug --no-dependencies
4>  Project AllReady.UnitTest (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
========== Build: 3 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by BBosman** [comment]
@stevejgordon  It looks like it can't find the typescript definition files from `@types/jquery` for some reason.

If you go to **Tools** -> **Extensions and Updates** can you tell me which version your `Typescript for Microsoft Visual Studio` is? And if there are updates available for it install those?

**Comment by c0g1t8** [comment]
@BBosman Based on the information that @stevejgordon provided in the Slack channel.  I was able to get things to build. 

- Did a tsc version check and the system returned Version 2.2.1
- Went to https://www.microsoft.com/en-us/download/details.aspx?id=48593
- Downloaded _TypeScript 2.1.4 for Visual Studio 2015_ and installed
- Restored Nuget packages for solution 

I've got a _clean_ dev VM based on https://developer.microsoft.com/en-us/windows/downloads/virtual-machines.  I'm going to clone HTBox/master to it and retest.

> development environments should be cows not pets 

😄

**Comment by c0g1t8** [comment]
Okay - I can confirm installing _TypeScript 2.1.4 for Visual Studio 2015_ solves the problem when doing a **Debug** build.  Don't know why.

But am now getting another issue doing a **Release** build.

```
`1>------ Build started: Project: AllReady.Core, Configuration: Release Any CPU ------
1>  C:\Program Files\dotnet\dotnet.exe build "C:\Repos\allReady\AllReadyApp\AllReady.Core" --configuration Release --no-dependencies
1>  Project AllReady.Core (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
2>------ Build started: Project: AllReady, Configuration: Release Any CPU ------
3>------ Build started: Project: AllReady.NotificationsWebJob, Configuration: Release Any CPU ------
3>  C:\Program Files\dotnet\dotnet.exe build "C:\Repos\allReady\AllReadyApp\AllReady.NotificationsWebJob" --configuration Release --no-dependencies
3>  Project AllReady.NotificationsWebJob (.NETFramework,Version=v4.6) was previously compiled. Skipping compilation.
2>  C:\Program Files\dotnet\dotnet.exe build "C:\Repos\allReady\AllReadyApp\Web-App\AllReady" --configuration Release --no-dependencies
2>  Project AllReady (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
2>  Compiling AllReady for .NETCoreApp,Version=v1.0
2>  C:\Program Files\dotnet\dotnet.exe compile-csc @C:\Repos\allReady\AllReadyApp\Web-App\AllReady\obj\Release\netcoreapp1.0\dotnet-compile.rsp returned Exit Code 1
2>C:\Repos\allReady\AllReadyApp\Web-App\AllReady\Controllers\TestHangfireController.cs(23,42): error CS0765: Partial methods with only a defining declaration or removed conditional methods cannot be used in expression trees
2>  Compilation failed.
2>      0 Warning(s)
2>      1 Error(s)
2>  Time elapsed 00:00:04.8491637
4>------ Build started: Project: AllReady.UnitTest, Configuration: Release Any CPU ------
4>  C:\Program Files\dotnet\dotnet.exe build "C:\Repos\allReady\AllReadyApp\Web-App\AllReady.UnitTest" --configuration Release --no-dependencies
4>  Project AllReady.UnitTest (.NETCoreApp,Version=v1.0) will be compiled because expected inputs are missing
4>  Compiling AllReady.UnitTest for .NETCoreApp,Version=v1.0
4>  C:\Program Files\dotnet\dotnet.exe compile-csc @C:\Repos\allReady\AllReadyApp\Web-App\AllReady.UnitTest\obj\Release\netcoreapp1.0\dotnet-compile.rsp returned Exit Code 1
4>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(262,5): error : C:\Repos\allReady\AllReadyApp\Web-App\AllReady.UnitTest\error CS0006: Metadata file 'C:\Repos\allReady\AllReadyApp\Web-App\AllReady\bin\Release\netcoreapp1.0\AllReady.dll' could not be found
4>  Compilation failed.
4>      0 Warning(s)
4>      1 Error(s)
4>  Time elapsed 00:00:00.5875761
========== Build: 2 succeeded, 2 failed, 1 up-to-date, 0 skipped ==========
```
The problem being
```
C:\Program Files\dotnet\dotnet.exe compile-csc @C:\Repos\allReady\AllReadyApp\Web-App\AllReady\obj\Release\netcoreapp1.0\dotnet-compile.rsp returned Exit Code 1
2>C:\Repos\allReady\AllReadyApp\Web-App\AllReady\Controllers\TestHangfireController.cs(23,42): error CS0765: Partial methods with only a defining declaration or removed conditional methods cannot be used in expression trees
2>  Compilation failed.
```

**Note:** I'm testing with the _AllReadyWebOnly.sln_

**Comment by c0g1t8** [comment]
The release build issue is a simple fix.  Just need to wrap the offending line as follows:
```
#if debug
            backgroundJob.Schedule(() => Debug.WriteLine("Scheduled Job completed successfully!"), TimeSpan.FromSeconds(5));
#endif
```

**Comment by BBosman** [comment]
@c0g1t8 Nice find on the release build issue and confirming my suspicion on the `Typescript for Microsoft Visual Studio` thing. 
 
I think we'll need some tweaks to [this](https://github.com/HTBox/allReady/blob/master/docs/prerequisite_install_guide/prerequisite_install_guide.md#configure-visual-studio-external-web-tools) document to mention the need for an updated `Typescript for Microsoft Visual Studio`. Biggest issue is getting some usable screenshots.

**Comment by c0g1t8** [comment]
@BBosman I've been researching this issue further and found some other _strangeness_.  I went back to my reference VM and started testing.
- Default version of Typescript installed with Visual Studio 2015 Update 3 is 1.8.36.0.
![image](https://cloud.githubusercontent.com/assets/23250332/23834408/49605b16-0713-11e7-9822-80333bcc3150.png)
- Command line build of the _.\AllReadyApp\Web-App\AllReady_ is successful.
- Building _AllReadyWebOnly.sln_ fails as reported.

❓ Is _AllReady.xproj_ out of sync with _project.json_?

**Comment by c0g1t8** [comment]
Clarification of my comment above

> - Did a tsc version check and the system returned Version 2.2.1
> - Went to https://www.microsoft.com/en-us/download/details.aspx?id=48593
> - Downloaded TypeScript 2.1.4 for Visual Studio 2015 and installed
> - Restored Nuget packages for solution
> - tsc version still returns Version 2.2.1 

The **tsc** version reported from the command line is not the version necessarily used by VS2015.3.  The **tsc** version used in VS2015.3 is reported in _Help|About_.

**Comment by c0g1t8** [comment]
@BBosman @tonysurma 

**General Comment on [Prerequisite Install Guide](https://github.com/HTBox/allReady/blob/master/docs/prerequisite_install_guide/prerequisite_install_guide.md#configure-visual-studio-external-web-tools)**

As a newbie to this project and not that familiar with _dotnetcore_, I approached this as more of a _Visual Studio user_.  I bascially followed the [Developer Setup](https://github.com/HTBox/allReady/wiki/Developer-Setup) only.

**Note:** I have preference for developing in a VM environment.
- Downloaded a pre-existing development Hyper-V VM from [here](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines).
- Booted, updated and patched the base OSof VM.
- Downloaded and installed the Long Term Support (LTS) version of the SDK.
- Cloned the repos and started building _AlReadyWebOnly.sln_.
- Got a number of errors.  I was missing some prerequisites such as F# and Cordova.  Those were pretty clear based on the error messages and hints provided by Visual Studio.
- Installed the prerequisites and built successfully.

It was remarkably simple and straight forward.  Well ☹️ until this issue arose.  I'm going to update the  [Developer Setup](https://github.com/HTBox/allReady/wiki/Developer-Setup) since it's more accessible. 😄

**Comment by stevejgordon** [comment]
@BBosman and @c0g1t8 - Thanks for sticking with this. I was having the build issue on my work machine which was running 1.8.36.0 (I thought it was newer!). Updated to 2.2.1.0 and it's now building.

**Comment by c0g1t8** [comment]
@BBosman and @stevejgordon Should we just standardize on version 2.2.1.0?  It's the most current version and I believe that is the version in Visual Studio 2017.

**Comment by BBosman** [comment]
That would be my preference. The newer version solves the issue of manually having to wire up definition files, lowering the barrier of entry for using/switching to TypeScript.

**Comment by stevejgordon** [comment]
Closing as by using 2.2.1.0 locally new contributors seem to be able to build correctly.

**Comment by c0g1t8** [comment]
Updating **Developer Setup** to reflect.
