### ISSUE TITLE
TimeTagHelper Test Failure

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#412]
When running the tests on my local machine I get the following test failure. Perhaps because I'm in the UK.

Perhaps @dpaquette can advise?

Test Name:	TimeTagHelperTests.ValueShouldBeFormattedUsingDefaultFormat
Test FullName:	AllReady.UnitTest.TagHelpers.TimeTagHelperTests.ValueShouldBeFormattedUsingDefaultFormat
Test Source:	E:\Software Development\Projects\AllReady\AllReadyApp\Web-App\AllReady.UnitTest\TagHelpers\TimeTagHelperTests.cs : line 31
Test Outcome:	Failed
Test Duration:	0:00:00.002

Result StackTrace:	
at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\StringAsserts.cs:line 239
   at Xunit.Assert.Equal(String expected, String actual) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\StringAsserts.cs:line 169
   at AllReady.UnitTest.TagHelpers.TimeTagHelperTests.ValueShouldBeFormattedUsingDefaultFormat() in E:\Software Development\Projects\AllReady\AllReadyApp\Web-App\AllReady.UnitTest\TagHelpers\TimeTagHelperTests.cs:line 39
Result Message:	
Assert.Equal() Failure
          ↓ (pos 0)
Expected: 12/25/2014 1:21 PM
Actual:   25/12/2014 13:21
          ↑ (pos 0)

**Comment by dpaquette** [comment]
@stevejgordon  this is definitely related to regional settings. You can safely ignore this for now and I will submit a PR to fix it today.

**Comment by dpaquette** [comment]
Please assign to me
